<!-- Each chapter is set to compile separately - include "global" set-up -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

CRAN_repo = getOption("repos")
CRAN_repo["CRAN"] = "http://cran.us.r-project.org"
options(repos = CRAN_repo)

if ( !require("here") )          { install.packages("here") };            require(here)
if ( !require("tidyverse") )     { install.packages("tidyverse") };       require(tidyverse)
if ( !require("ggtext") )        { install.packages("ggtext") };          require(ggtext)
if ( !require("pBrackets") )     { install.packages("pBrackets") };       require(pBrackets)
if ( !require("htmlwidgets") )   { install.packages("htmlwidgets") };     require(htmlwidgets)
if ( !require("plotly") )        { install.packages("plotly") };          require(plotly)
if ( !require("formattable") )   { install.packages("formattable") };     require(formattable)
if ( !require("kableExtra") )    { install.packages("kableExtra") };      require(kableExtra)
if ( !require("rtsdata") )       { install.packages("rtsdata") };         require(rtsdata)
if ( !require("PerformanceAnalytics") )     { install.packages("PerformanceAnalytics") };   require(PerformanceAnalytics)
if ( !require("anytime") )       { install.packages("anytime") };         require(anytime)
if ( !require("gridExtra") )     { install.packages("gridExtra")};        require(gridExtra)

options(kableExtra.html.bsTable = TRUE)
options(kableExtra.auto_format = FALSE)
```

```{r Set-Global-Chapter-Variables}
plot_bg <- "#FFFFFF" # "#191919"
plot_fg <- "#000000" # #929292"
plot_fg_alt <- "#969696" # ??
vline_color <- "#D2B48C"

save_tables_as_pictures <- FALSE
load_table_pictures <- TRUE
out_width_plot <- "80%"
out_width_table <- "90%"

grid::grid.locator(unit="npc") 
output_epub = knitr::opts_knit$get("rmarkdown.pandoc.to") == "epub3"
source("Plotting_Functions.R")
```

```{r Table-Helper-Functions}
at_least_number <- function(x,number) {
  ifelse( typeof(x) == "character", 
          return( as.numeric(gsub('\\(','-',gsub('[)$,]', '', x))) >= number ),
          return( x >= number) )
}

remove_negative_zeros <- function(x) { (x[which(-1e-4 < x & x < 1e-4)] = 0); return(x) }
```

# Advanced Volatility

## The VIX Index

```{r SPY-Price-Volatility-Plots-2018, fig.align = "center", out.width = out_width_plot, echo = FALSE, message = FALSE}
### The buy and sell regions are manually annoted (by me) 
Color <- rep("black", 271)
Color[ 1:271 %in% ( 20 + c(0) ) ] <- "green" 
Color[ 1:271 %in% ( 20 + c(0) ) ] <- "red"

SP500_Price_data_2018 <- ds.getSymbol.yahoo("^GSPC", from = "2017-12-01", to = "2019-01-01")
SP500_Price_data_2018 <- tibble( "Date" = as.Date(as.character(index(SP500_Price_data_2018))), 
                                 "Price" = as.vector(SP500_Price_data_2018$GSPC.Adjusted),
                                 Color = Color )

SP500_Volatility_data_2018 <- read.csv("vixcurrent.csv", header = TRUE, sep = ",", 
                                   stringsAsFactors = FALSE, skip = 1)
SP500_Volatility_data_2018$Date <- anydate( SP500_Volatility_data_2018$Date )
SP500_Volatility_data_2018 <- SP500_Volatility_data_2018[ anydate("2017-12-01") <= SP500_Volatility_data_2018$Date
                                                          & SP500_Volatility_data_2018$Date <= anydate("2018-12-31"), ]

SP500_Volatility_data_2018 <- tibble( "Date" = SP500_Volatility_data_2018$Date,
                                      "Volatility" = SP500_Volatility_data_2018$VIX.Close,
                                      "Color" = Color )  

SP500_Price_plot <- ggplot() + 
  geom_line(data = SP500_Price_data_2018, aes(x = Date, y = Price, color = Color, group = 1)) +
  geom_vline(xintercept = anydate("2018-01-01"), linetype = "dotted", color = vline_color, size = 1) + 
  scale_y_continuous(label = scales::dollar) +
  labs(title = "S&P 500: Daily Prices for 2018.", x = "", y = "") +
  scale_x_date(date_labels = "%B") +
  scale_color_manual(values = c( "black" = "black", "red" = "red", "green" = "green")) + 
  options_theme() 

SP500_Volatility_Chart <- ggplot() + 
  geom_line(data = SP500_Volatility_data_2018, 
            aes(x = anydate(Date), y = Volatility, color = Color, group = 1)) +
  geom_vline(xintercept = anydate("2018-01-01"), linetype = "dotted", color = vline_color, size = 1) + 
  labs(title = "S&P 500 Daily Volatility for 2018.", x = "", y = "") +
  scale_color_manual(values = c( "black" = "black", "red" = "red", "green" = "green")) + 
  scale_x_date(date_labels = "%B") +
  options_theme() 

# Plot the price and volatility charts side-by-side
grid.arrange(SP500_Price_plot, SP500_Volatility_Chart, ncol=1)
```

```{r SPY-Price-Volatility-Plots-2019, fig.align = "center", out.width = out_width_plot, echo = FALSE, message = FALSE}
### The buy and sell regions are manually annoted (by me) 
Color <- rep("black", 252)
Color[ 1:252 %in% ( 20 + c(0) ) ] <- "green" 
Color[ 1:252 %in% ( 20 + c(0) ) ] <- "red"

SP500_Price_data_2019 <- ds.getSymbol.yahoo("^GSPC", from = "2019-01-01", to = "2020-01-01")
SP500_Price_data_2019 <- tibble( "Date" = as.Date(as.character(index(SP500_Price_data_2019))), 
                                 "Price" = as.vector(SP500_Price_data_2019$GSPC.Adjusted),
                                 Color = Color )

SP500_Volatility_data_2019 <- read.csv("vixcurrent.csv", header = TRUE, sep = ",", 
                                   stringsAsFactors = FALSE, skip = 1)
SP500_Volatility_data_2019$Date <- anydate( SP500_Volatility_data_2019$Date )
SP500_Volatility_data_2019 <- SP500_Volatility_data_2019[ anydate("2019-01-01") <= SP500_Volatility_data_2019$Date
                                                          & SP500_Volatility_data_2019$Date <= anydate("2019-12-31"), ]

SP500_Volatility_data_2019 <- tibble( "Date" = SP500_Volatility_data_2019$Date,
                                      "Volatility" = SP500_Volatility_data_2019$VIX.Close,
                                      "Color" = Color )  

SP500_Price_plot <- ggplot() + 
  geom_line(data = SP500_Price_data_2019, aes(x = Date, y = Price, color = Color, group = 1)) +
  scale_y_continuous(label = scales::dollar) +
  labs(title = "S&P 500: Daily Prices for 2019.", x = "", y = "") +
  scale_x_date(date_labels = "%B") +
  scale_color_manual(values = c( "black" = "black", "red" = "red", "green" = "green")) + 
  options_theme() 

SP500_Volatility_Chart <- ggplot() + 
  geom_line(data = SP500_Volatility_data_2019, 
            aes(x = anydate(Date), y = Volatility, color = Color, group = 1)) +
  labs(title = "VIX Index: Daily Closing Prices for 2019.", x = "", y = "") +
  scale_color_manual(values = c( "black" = "black", "red" = "red", "green" = "green")) + 
  scale_x_date(date_labels = "%B") +
  options_theme() 

# Plot the price and volatility charts side-by-side
grid.arrange(SP500_Price_plot, SP500_Volatility_Chart, ncol=1)
```


## The MOVE Index

```{r T-Bond-Price-Volatility-Plots-2018, fig.align = "center", out.width = out_width_plot, echo = FALSE, message = FALSE}
### The buy and sell regions are manually annoted (by me) 
Color <- rep("black", 271)
TBond_Price_data_2018 <- ds.getSymbol.yahoo("IEF", from = "2017-12-01", to = "2019-01-01")
TBond_Price_data_2018 <- tibble( "Date" = as.Date(as.character(index(TBond_Price_data_2018))), 
                                  "Price" = as.vector(TBond_Price_data_2018$IEF.Adjusted),
                                  Color = Color )

TBond_Volatility_data_2018 <- read.csv("MOVE_Historical_Data.csv", header = TRUE, sep = ",", 
                                   stringsAsFactors = FALSE)
TBond_Volatility_data_2018$Date <- anydate( TBond_Volatility_data_2018$Date )
TBond_Volatility_data_2018 <- TBond_Volatility_data_2018[ anydate("2017-12-01") <= TBond_Volatility_data_2018$Date
                                                          & TBond_Volatility_data_2018$Date <= anydate("2018-12-31"), ]

TBond_Price_data_2018 <- TBond_Price_data_2018[TBond_Price_data_2018$Date %in% TBond_Volatility_data_2018$Date, ]
Color <- rep("black", 263)
Color[ 1:263 %in% ( 20 + c(0) ) ] <- "green" 
Color[ 1:263 %in% ( 20 + c(0) ) ] <- "red"

TBond_Volatility_data_2018 <- tibble( "Date" = TBond_Volatility_data_2018$Date,
                                      "Volatility" = TBond_Volatility_data_2018$Price,
                                      "Color" = Color )  

TBond_Price_plot <- ggplot() + 
  geom_line(data = TBond_Price_data_2018, aes(x = Date, y = Price, color = Color, group = 1)) +
  geom_vline(xintercept = anydate("2018-01-01"), linetype = "dotted", color = vline_color, size = 1) + 
  scale_y_continuous(label = scales::dollar) +
  labs(title = "IEF: Daily Prices for 2018.", x = "", y = "") +
  scale_x_date(date_labels = "%B") +
  scale_color_manual(values = c( "black" = "black", "red" = "red", "green" = "green")) + 
  options_theme() 

TBond_Volatility_Chart <- ggplot() + 
  geom_line(data = TBond_Volatility_data_2018, 
            aes(x = anydate(Date), y = Volatility, color = Color, group = 1)) +
  geom_vline(xintercept = anydate("2018-01-01"), linetype = "dotted", color = vline_color, size = 1) + 
  labs(title = "MOVE Index: Daily Closing Prices for 2018.", x = "", y = "") +
  scale_color_manual(values = c( "black" = "black", "red" = "red", "green" = "green")) + 
  scale_x_date(date_labels = "%B") +
  options_theme() 

# Plot the price and volatility charts side-by-side
grid.arrange(TBond_Price_plot, TBond_Volatility_Chart, ncol=1)
```


```{r T-Bond-Price-Volatility-Plots-2019, fig.align = "center", out.width = out_width_plot, echo = FALSE, message = FALSE}
### The buy and sell regions are manually annoted (by me) 
Color <- rep("black", 252)
TBond_Price_data_2019 <- ds.getSymbol.yahoo("IEF", from = "2019-01-01", to = "2020-01-01")
TBond_Price_data_2019 <- tibble( "Date" = as.Date(as.character(index(TBond_Price_data_2019))), 
                                  "Price" = as.vector(TBond_Price_data_2019$IEF.Adjusted),
                                  Color = Color )

TBond_Volatility_data_2019 <- read.csv("MOVE_Historical_Data.csv", header = TRUE, sep = ",", 
                                   stringsAsFactors = FALSE)
TBond_Volatility_data_2019$Date <- anydate( TBond_Volatility_data_2019$Date )
TBond_Volatility_data_2019 <- TBond_Volatility_data_2019[ anydate("2019-01-01") <= TBond_Volatility_data_2019$Date
                                                          & TBond_Volatility_data_2019$Date <= anydate("2019-12-31"), ]

TBond_Price_data_2019 <- TBond_Price_data_2019[TBond_Price_data_2019$Date %in% TBond_Volatility_data_2019$Date, ]
TBond_Volatility_data_2019 <- TBond_Volatility_data_2019[TBond_Volatility_data_2019$Date %in% TBond_Price_data_2019$Date, ]
Color <- rep("black", 250)
Color[ 1:250 %in% ( 20 + c(0) ) ] <- "green" 
Color[ 1:250 %in% ( 20 + c(0) ) ] <- "red"

TBond_Volatility_data_2019 <- tibble( "Date" = TBond_Volatility_data_2019$Date,
                                      "Volatility" = TBond_Volatility_data_2019$Price,
                                      "Color" = Color )  

TBond_Price_plot <- ggplot() + 
  geom_line(data = TBond_Price_data_2019, aes(x = Date, y = Price, color = Color, group = 1)) +
  scale_y_continuous(label = scales::dollar) +
  labs(title = "IEF: Daily Prices for 2019.", x = "", y = "") +
  scale_x_date(date_labels = "%B") +
  scale_color_manual(values = c( "black" = "black", "red" = "red", "green" = "green")) + 
  options_theme() 

TBond_Volatility_Chart <- ggplot() + 
  geom_line(data = TBond_Volatility_data_2019, 
            aes(x = anydate(Date), y = Volatility, color = Color, group = 1)) +
  labs(title = "MOVE Index: Daily Closing Prices for 2019.", x = "", y = "") +
  scale_color_manual(values = c( "black" = "black", "red" = "red", "green" = "green")) + 
  scale_x_date(date_labels = "%B") +
  options_theme() 

# Plot the price and volatility charts side-by-side
grid.arrange(TBond_Price_plot, TBond_Volatility_Chart, ncol=1)
```


## The Volatility Surface 

