<!-- Each chapter is set to compile separately - include "global" set-up -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Source: https://davidgohel.github.io/officedown/articles/captions.html
knitr::opts_chunk$set(
  fig.cap.style = "Image Caption",
  fig.cap.pre = "", fig.cap.sep = "")

knitr::opts_chunk$set(
  tab.cap.style = "Table Caption",
  tab.cap.pre = "", tab.cap.sep = "")

CRAN_repo = getOption("repos")
CRAN_repo["CRAN"] = "http://cran.us.r-project.org"
options(repos = CRAN_repo)

if ( !require("here") )          { install.packages("here") };            require(here)
if ( !require("tidyverse") )     { install.packages("tidyverse") };       require(tidyverse)
if ( !require("ggtext") )        { install.packages("ggtext") };          require(ggtext)
if ( !require("pBrackets") )     { install.packages("pBrackets") };       require(pBrackets)
if ( !require("htmlwidgets") )   { install.packages("htmlwidgets") };     require(htmlwidgets)
if ( !require("plotly") )        { install.packages("plotly") };          require(plotly)
if ( !require("formattable") )   { install.packages("formattable") };     require(formattable)
if ( !require("kableExtra") )    { install.packages("kableExtra") };      require(kableExtra)
if ( !require("grid") )          { install.packages("grid") };            require(grid)
if ( !require("magick") )        { install.packages("magick") };          require(magick)
if ( !require("gridExtra") )     { install.packages("gridExtra") };       require(gridExtra)
if ( !require("derivmkts") )     { install.packages("derivmkts") };       require(derivmkts)

options(kableExtra.html.bsTable = TRUE)
options(kableExtra.auto_format = FALSE)

out_width_plot <- "97.5%"
out_width_table <- "97.5%"
grid::grid.locator(unit="npc") 

plot_bg <- "#FFFFFF"
plot_fg <- "#000000" 
plot_fg_alt <- "#969696" 

source("Plotting_Functions.R")
```

```{r Table-Helper-Functions}
at_least_number <- function(x,number) {
  ifelse( typeof(x) == "character", 
          return( as.numeric(gsub('\\(','-',gsub('[)$,]', '', x))) >= number ),
          return( x >= number) )
}

remove_negative_zeros <- function(x) { (x[which(-1e-4 < x & x < 1e-4)] = 0); return(x) }
```


# Thinking in Greeks II {#Second-Greeks}

So far, we've covered *delta* and *gamma*. There are three major greeks left -- *vega*, *theta*, and *rho*. *Rho* is related to interest rates, so we'll see it in the next chapter about long-term options. *Vega* and *theta* are both related to volatility, so we'll be taking them on together in this chapter. 

## Vega

```{r XYZ-Straddle-Lognormal-Over-K-Small-SD, fig.align = "center", out.width = out_width_plot, message = FALSE}
Call_cost <- 10; Put_cost <- 15
Call_K <- 200; Put_K <- 200
x_min <- 120; x_max = 280
Stock_cost <- 200

Breakeven_right <- Put_K - Put_cost - Call_cost
Breakeven_left <- Call_K + Call_cost + Put_cost

Call_Payoff_XYZ <- tibble( "Call_x" = seq(from = x_min, to = x_max, by = 0.01),
                            "Call_y" = -Call_cost + (Call_x > Call_K)*(Call_x-Call_K),
                            "Profitable" = ifelse(-Call_cost + (Call_x > Call_K)*(Call_x-Call_K) > 0, 
                                                      "Profit_call","Loss_call") )

Put_Payoff_XYZ <- tibble( "Put_x" = seq(from = x_min, to = x_max, by = 0.01),
                          "Put_y" = -Put_cost - (Put_x < Put_K) * (Put_x - Put_K),
                          "Profitable" = ifelse(-Put_cost - (Put_x < Put_K) * (Put_x - Put_K) >= 0,
                                                "Profit_put", "Loss_put") )

Straddle_Payoff_XYZ_left <- tibble( "Straddle_x" = seq(from = x_min, to = Breakeven_right, by = 0.01),
                                     "Straddle_y" = -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                     - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K),
                                     "Profitable" = ifelse( -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                                            - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K) > 0, 
                                                            "Profit_right_straddle","Loss_right_straddle") )  

Straddle_Payoff_XYZ_center <- tibble( "Straddle_x" = seq(from = Breakeven_right, to = Breakeven_left, by = 0.01),
                                      "Straddle_y" = -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                      - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K),
                                      "Profitable" = ifelse( -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                                             - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K) > 0, 
                                                            "Profit_center_straddle","Loss_center_straddle") )  

Straddle_Payoff_XYZ_right <- tibble( "Straddle_x" = seq(from = Breakeven_left, to = x_max, by = 0.01),
                                    "Straddle_y" = -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                    - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K),
                                    "Profitable" = ifelse( -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                                           - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K) > 0, 
                                                           "Profit_right_straddle","Loss_right_straddle") )  

Straddle_Payoff_Lognormal <- tibble( "Dist_x" = seq(from = x_min, to = x_max, by = 0.01), 
                                     "Dist_y" = 10 * 1000 * (45/200) * dlnorm(Dist_x, meanlog = log(200), sdlog = log(1.11)) )

# qlnorm( 0.10, meanlog = log(200), sdlog = log(1.11) )
# qlnorm( 0.87, meanlog = log(200), sdlog = log(1.11) )

temp <- straddle_payoff_dist_overlay_volatility( data_straddle_left = Straddle_Payoff_XYZ_left,
                                      data_straddle_center = Straddle_Payoff_XYZ_center,
                                      data_straddle_right = Straddle_Payoff_XYZ_right,
                                      data_distribution_overlay = Straddle_Payoff_Lognormal, 
                                      fill_rgb = col2rgb("cornflowerblue"),
                                      main_title = "Straddle: Scenario 1",
                                      sub_title = "",
                                      # sub_title = "The market's view of the price of\nXYZ's shares on the expiry date.",
                                      curve_text_1 = "10%",
                                      curve_text_x_1 = 165, 
                                      curve_text_y_1 = 4,
                                      curve_text_2 = "13%",
                                      curve_text_x_2 = 237.5, 
                                      curve_text_y_2 = 4)
y_axis_labels <- na.omit( ggplot_build(temp)$layout$panel_params[[1]]$y$get_labels() )
y_axis_labels <- as.numeric(gsub('\\(','-',gsub('[)$,]', '', y_axis_labels)))
tick_color <- ifelse( as.numeric(gsub('\\(','-',gsub('[)$,]', '', y_axis_labels))) < 0,
                      "red", "green3" )

temp <- temp + theme( axis.text.y = element_markdown(colour = tick_color) )
temp; rm(temp)
```

```{r XYZ-Straddle-Lognormal-Over-K-Medium-SD, fig.align = "center", out.width = out_width_plot, message = FALSE}
Call_cost <- 10; Put_cost <- 15
Call_K <- 200; Put_K <- 200
x_min <- 120; x_max = 280
Stock_cost <- 200

Breakeven_right <- Put_K - Put_cost - Call_cost
Breakeven_left <- Call_K + Call_cost + Put_cost

Call_Payoff_XYZ <- tibble( "Call_x" = seq(from = x_min, to = x_max, by = 0.01),
                            "Call_y" = -Call_cost + (Call_x > Call_K)*(Call_x-Call_K),
                            "Profitable" = ifelse(-Call_cost + (Call_x > Call_K)*(Call_x-Call_K) > 0, 
                                                      "Profit_call","Loss_call") )

Put_Payoff_XYZ <- tibble( "Put_x" = seq(from = x_min, to = x_max, by = 0.01),
                          "Put_y" = -Put_cost - (Put_x < Put_K) * (Put_x - Put_K),
                          "Profitable" = ifelse(-Put_cost - (Put_x < Put_K) * (Put_x - Put_K) >= 0,
                                                "Profit_put", "Loss_put") )

Straddle_Payoff_XYZ_left <- tibble( "Straddle_x" = seq(from = x_min, to = Breakeven_right, by = 0.01),
                                     "Straddle_y" = -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                     - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K),
                                     "Profitable" = ifelse( -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                                            - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K) > 0, 
                                                            "Profit_right_straddle","Loss_right_straddle") )  

Straddle_Payoff_XYZ_center <- tibble( "Straddle_x" = seq(from = Breakeven_right, to = Breakeven_left, by = 0.01),
                                      "Straddle_y" = -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                      - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K),
                                      "Profitable" = ifelse( -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                                             - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K) > 0, 
                                                            "Profit_center_straddle","Loss_center_straddle") )  

Straddle_Payoff_XYZ_right <- tibble( "Straddle_x" = seq(from = Breakeven_left, to = x_max, by = 0.01),
                                    "Straddle_y" = -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                    - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K),
                                    "Profitable" = ifelse( -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                                           - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K) > 0, 
                                                           "Profit_right_straddle","Loss_right_straddle") )  

Straddle_Payoff_Lognormal <- tibble( "Dist_x" = seq(from = x_min, to = x_max, by = 0.01), 
                                     "Dist_y" = 10 * 1000 * (45/200) * dlnorm(Dist_x, meanlog = log(200), sdlog = log(1.13)) )

# qlnorm( 0.1375, meanlog = log(200), sdlog = log(1.13) )
# qlnorm( 0.8325, meanlog = log(200), sdlog = log(1.13) )

temp <- straddle_payoff_dist_overlay_volatility( data_straddle_left = Straddle_Payoff_XYZ_left,
                                      data_straddle_center = Straddle_Payoff_XYZ_center,
                                      data_straddle_right = Straddle_Payoff_XYZ_right,
                                      data_distribution_overlay = Straddle_Payoff_Lognormal, 
                                      fill_rgb = col2rgb("cornflowerblue"),
                                      main_title = "Straddle: Scenario 2",
                                      sub_title = "", 
                                      # sub_title = "The market's view of the price of\nXYZ's shares on the expiry date.",
                                      curve_text_1 = "13.75%",
                                      curve_text_x_1 = 162.5, 
                                      curve_text_y_1 = 4,
                                      curve_text_2 = "16.75%",
                                      curve_text_x_2 = 240, 
                                      curve_text_y_2 = 4)
y_axis_labels <- na.omit( ggplot_build(temp)$layout$panel_params[[1]]$y$get_labels() )
y_axis_labels <- as.numeric(gsub('\\(','-',gsub('[)$,]', '', y_axis_labels)))
tick_color <- ifelse( as.numeric(gsub('\\(','-',gsub('[)$,]', '', y_axis_labels))) < 0,
                      "red", "green3" )

temp <- temp + theme( axis.text.y = element_markdown(colour = tick_color) )
temp; rm(temp)
```

```{r XYZ-Straddle-Lognormal-Over-K-Large-SD, fig.align = "center", out.width = out_width_plot, message = FALSE}
Call_cost <- 10; Put_cost <- 15
Call_K <- 200; Put_K <- 200
x_min <- 120; x_max = 280
Stock_cost <- 200

Breakeven_right <- Put_K - Put_cost - Call_cost
Breakeven_left <- Call_K + Call_cost + Put_cost

Call_Payoff_XYZ <- tibble( "Call_x" = seq(from = x_min, to = x_max, by = 0.01),
                            "Call_y" = -Call_cost + (Call_x > Call_K)*(Call_x-Call_K),
                            "Profitable" = ifelse(-Call_cost + (Call_x > Call_K)*(Call_x-Call_K) > 0, 
                                                      "Profit_call","Loss_call") )

Put_Payoff_XYZ <- tibble( "Put_x" = seq(from = x_min, to = x_max, by = 0.01),
                          "Put_y" = -Put_cost - (Put_x < Put_K) * (Put_x - Put_K),
                          "Profitable" = ifelse(-Put_cost - (Put_x < Put_K) * (Put_x - Put_K) >= 0,
                                                "Profit_put", "Loss_put") )

Straddle_Payoff_XYZ_left <- tibble( "Straddle_x" = seq(from = x_min, to = Breakeven_right, by = 0.01),
                                     "Straddle_y" = -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                     - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K),
                                     "Profitable" = ifelse( -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                                            - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K) > 0, 
                                                            "Profit_right_straddle","Loss_right_straddle") )  

Straddle_Payoff_XYZ_center <- tibble( "Straddle_x" = seq(from = Breakeven_right, to = Breakeven_left, by = 0.01),
                                      "Straddle_y" = -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                      - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K),
                                      "Profitable" = ifelse( -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                                             - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K) > 0, 
                                                            "Profit_center_straddle","Loss_center_straddle") )  

Straddle_Payoff_XYZ_right <- tibble( "Straddle_x" = seq(from = Breakeven_left, to = x_max, by = 0.01),
                                    "Straddle_y" = -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                    - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K),
                                    "Profitable" = ifelse( -Put_cost - (Straddle_x < Put_K) * (Straddle_x - Put_K) 
                                                           - Call_cost + (Straddle_x > Call_K)*(Straddle_x-Call_K) > 0, 
                                                           "Profit_right_straddle","Loss_right_straddle") )  

Straddle_Payoff_Lognormal <- tibble( "Dist_x" = seq(from = x_min, to = x_max, by = 0.01), 
                                     "Dist_y" = 10 * 1000 * (45/200) * dlnorm(Dist_x, meanlog = log(200), sdlog = log(1.16)) )

# qlnorm( 0.184, meanlog = log(200), sdlog = log(1.16) )
# qlnorm( 0.786, meanlog = log(200), sdlog = log(1.16) )

temp <- straddle_payoff_dist_overlay_volatility( data_straddle_left = Straddle_Payoff_XYZ_left,
                                      data_straddle_center = Straddle_Payoff_XYZ_center,
                                      data_straddle_right = Straddle_Payoff_XYZ_right,
                                      data_distribution_overlay = Straddle_Payoff_Lognormal, 
                                      fill_rgb = col2rgb("cornflowerblue"),
                                      main_title = "Straddle: Scenario 3",
                                      sub_title = "", 
                                      # sub_title = "The market's view of the price of\nXYZ's shares on the expiry date.",
                                      curve_text_1 = "18.4%",
                                      curve_text_x_1 = 160,
                                      curve_text_y_1 = 4,
                                      curve_text_2 = "21.4%",
                                      curve_text_x_2 = 242.50, 
                                      curve_text_y_2 = 5)
y_axis_labels <- na.omit( ggplot_build(temp)$layout$panel_params[[1]]$y$get_labels() )
y_axis_labels <- as.numeric(gsub('\\(','-',gsub('[)$,]', '', y_axis_labels)))
tick_color <- ifelse( as.numeric(gsub('\\(','-',gsub('[)$,]', '', y_axis_labels))) < 0,
                      "red", "green3" )

temp <- temp + theme( axis.text.y = element_markdown(colour = tick_color) )
temp; rm(temp)
```

```{r XYZ-Vega-3-Months-Before-Expiry-200, echo = FALSE, out.width = out_width_plot, fig.align = "center", message = FALSE, warning = FALSE, eval=FALSE}
Call_K <- 200
Current_price <- 200
x_min = 140; x_max = 260
Vega_x <- seq(from = 0.05, to = 0.25, by = 0.01)

Call_price <- bscall(s = 200, k = 200, v = Vega_x, r = 0.02, tt = 0.25, d = 0)
Call_cost <- 15 # bscall(s = 200, k = 200, v = 0.16, r = 0.02, tt = 0.25, d = 0)
Call_payoff <- Call_price - Call_cost
Call_vega <- greeks( bscall(s = 200, k = 200, v = Vega_x, 
                             r = 0.02, tt = 0.25, d = 0) )[4,]

idx_1 <- 8 # which(Vega_x == 0.12)
tangent_line_1 <- Call_vega[idx_1] * Vega_x
tangent_line_1 <- tangent_line_1 - tangent_line_1[idx_1] + Call_payoff[idx_1]

idx_2 <- which(Vega_x == 0.16)
tangent_line_2 <- Call_vega[idx_2] * Vega_x 
tangent_line_2 <- tangent_line_2 - tangent_line_2[idx_2] + Call_payoff[idx_2]

idx_3 <- which(Vega_x == 0.24)
tangent_line_3 <- Call_vega[idx_3] * Vega_x
tangent_line_3 <- tangent_line_3 - tangent_line_3[idx_3] + Call_payoff[idx_3]


Call_Vega_XYZ_200_3months <- tibble( "Vega_x" = seq(from = 0.05, to = 0.25, by = 0.01),
                       "Call_payoff" = currency(Call_payoff), 
                       "Call_vega_first" = tangent_line_1,
                       "Call_vega_second" = tangent_line_2,
                       "Call_vega_third" = tangent_line_3,
                       "Vega_first" = ifelse( abs(Vega_x-0.12) < 0.05,"Show_vega_first","Hide_vega_first"), 
                       "Vega_second" = ifelse( abs(Vega_x-0.16) < 0.05, "Show_vega_second","Hide_vega_second"), 
                       "Vega_third" = ifelse( abs(Vega_x-0.24) < 0.05, "Show_vega_third","Hide_vega_third") )

annotate_arrow_1 <- data.frame(x1 = 160, x2 = 160, y1 = 0, y2 = -10)
annotate_arrow_2 <- data.frame(x1 = 200-1, x2 = 200-1, y1 = 7.5, y2 = -2.5)
annotate_arrow_3 <- data.frame(x1 = 240-2.5, x2 = 240-2.5, y1 = 42.5, y2 = 32.5)

temp <- call_vega_before_expiry_payoff( call_vega_before_expiry = Call_Vega_XYZ_200_3months, 
                                        main_title = "Buy 1 XYZ call at the $200 strike",
                                        sub_title = "Payoff 3 months before expiry.")

temp <- temp + scale_y_continuous(label = scales::dollar, limits = c(-15,0))

y_axis_labels <- na.omit( ggplot_build(temp)$layout$panel_params[[1]]$y$get_labels() )
y_axis_labels <- as.numeric(gsub('\\(','-',gsub('[)$,]', '', y_axis_labels)))
tick_color <- ifelse( as.numeric(gsub('\\(','-',gsub('[)$,]', '', y_axis_labels))) < 0, "red", "green3" )

temp <- temp + theme( axis.text.y = element_markdown(colour = tick_color) ) 
        # annotate( geom = "text", x = 150, y = 7.5, color = "gray50", hjust = 0, 
        #           label = paste0("Stock: $160\nDelta: 0.009"), size = 4 ) + 
        # annotate( geom = "text", x = 190, y = 15, color = "gray50", hjust = 0, 
        #           label = paste0("Stock: $200\nDelta: 0.540"), size = 4 ) +
        # annotate( geom = "text", x = 227.5, y = 50, color = "gray50", hjust = 0, 
        #           label = paste0("Stock: $240\nDelta: 0.984"), size = 4 ) + 
        # geom_curve( aes(x = x1, y = y1, xend = x2, yend = y2), data = annotate_arrow_1,
        #             arrow = arrow(length = unit(0.03, "npc")), color = "gray50" ) + 
        # geom_curve( aes(x = x1, y = y1, xend = x2, yend = y2), data = annotate_arrow_2,
        #             arrow = arrow(length = unit(0.03, "npc")), color = "gray50" ) + 
        # geom_curve( aes(x = x1, y = y1, xend = x2, yend = y2), data = annotate_arrow_3,
        #             arrow = arrow(length = unit(0.03, "npc")), color = "gray50" ) + 
        # annotate( geom = "text", x = Call_K+Call_cost-11, y = -20, color = "green3", hjust = 0,
        #           label = paste0("Breakeven: ", scales::dollar(Call_K+Call_cost)), size = 4 ) + 
        # annotate( geom = "text", x = Call_K+Call_cost-11, y = -20, color = "red", hjust = 0,
        #           label = "Breakev", size = 4 ) 

temp; rm(temp)
```

## Theta

```{r XYZ-Theta-Over-Time-200, echo = FALSE, out.width = out_width_plot, fig.align = "center", message = FALSE, warning = FALSE}
Call_K <- 200
Current_price <- 200
x_min = 140; x_max = 260
Call_x <- seq(from = x_min, to = x_max, by = 0.1)
Theta_x <- rev( seq( from = 1, to = 2 * 252, by = 1 ) )

Call_price_high_vol <- bscall(s = 200, k = 200, v = 0.24, r = 0.02, tt = Theta_x/252, d = 0)
Call_cost_high_vol <- 15 # bscall(s = 200, k = 200, v = 0.16, r = 0.02, tt = 0, d = 0)
Call_payoff_high_vol <- Call_price_high_vol - Call_cost_high_vol
Call_theta_high_vol <- greeks( bscall(s = 200, k = 200, v = 0.24, 
                                      r = 0.02, tt = Theta_x/252, d = 0) )[6,] 

Call_price_medium_vol <- bscall(s = 200, k = 200, v = 0.16, r = 0.02, tt = Theta_x/252, d = 0)
Call_cost_medium_vol <- 15 # bscall(s = 200, k = 200, v = 0.16, r = 0.02, tt = 0.25, d = 0)
Call_payoff_medium_vol <- Call_price_medium_vol - Call_cost_medium_vol
Call_theta_medium_vol <- greeks( bscall(s = 200, k = 200, v = 0.16, 
                                        r = 0.02, tt = Theta_x/252, d = 0) )[6,] 

Call_price_low_vol <- bscall(s = 200, k = 200, v = 0.12, r = 0.02, tt = Theta_x/252, d = 0)
Call_cost_low_vol <- 15 # bscall(s = 200, k = 200, v = 0.16, r = 0.02, tt = 0.5, d = 0)
Call_payoff_low_vol <- Call_price_low_vol - Call_cost_low_vol
Call_theta_low_vol <- greeks( bscall(s = 200, k = 200, v = 0.12, 
                                     r = 0.02, tt = Theta_x/252, d = 0) )[6,] 

Call_Theta_XYZ_200_High_Vol <- tibble( "Theta_x" = Theta_x,
                                       "Price_y" = Call_price_high_vol,
                                       "Theta_y" = Call_theta_high_vol,
                                       "Color_High" = rep(TRUE, length(Theta_x)) )

Call_Theta_XYZ_200_Medium_Vol <- tibble( "Theta_x" = Theta_x,
                                         "Price_y" = Call_price_medium_vol,
                                         "Theta_y" = Call_theta_medium_vol,
                                         "Color_Med" = rep(TRUE, length(Theta_x)) )

Call_Theta_XYZ_200_Low_Vol <- tibble( "Theta_x" = Theta_x,
                                      "Price_y" = Call_price_low_vol,
                                      "Theta_y" = Call_theta_low_vol,
                                      "Color_Low" = rep(TRUE, length(Theta_x)) )

annotate_arrow_1 <- data.frame(x1 = 420, x2 = 420, y1 = 10, y2 = 14.5)
annotate_arrow_2 <- data.frame(x1 = 455, x2 = 460, y1 = 25, y2 = 21.5)
annotate_arrow_3 <- data.frame(x1 = 250, x2 = 250, y1 = 27.5, y2 = 22.5)

temp <- call_theta_over_time( call_theta_high_vol = Call_Theta_XYZ_200_High_Vol, # 370
                              call_theta_medium_vol = Call_Theta_XYZ_200_Medium_Vol, # 244
                              call_theta_low_vol = Call_Theta_XYZ_200_Low_Vol, # 116
                              main_title = "Buy 1 XYZ call at the $200 strike",
                              sub_title = "Compare Theta Decay At Different Levels of Volatility.") 

y_axis_labels <- na.omit( ggplot_build(temp)$layout$panel_params[[1]]$y$get_labels() )
y_axis_labels <- as.numeric(gsub('\\(','-',gsub('[)$,]', '', y_axis_labels)))
tick_color <- ifelse( as.numeric(gsub('\\(','-',gsub('[)$,]', '', y_axis_labels))) < 0, "red", "green3" )

temp <- temp + theme( axis.text.y = element_markdown(colour = tick_color) ) + 
        scale_x_reverse() + xlab("Days to Expiry") + 
        theme( axis.title.x = element_text(size = 12, colour = "grey50") ) +
        annotate( geom = "text", x = 455, y = 8.5, color = "gray35", hjust = 0,
                  label = paste0("Volatility: 12"), size = 4 ) +
        annotate( geom = "text", x = 504-116, y = 16, color = "gray35", hjust = 0,
                  label = paste0("$15"), size = 4 ) +
        annotate("point", x = 504-116, y = 15, colour = "gray35") + 
        annotate( geom = "text", x = 450, y = 25, color = "purple", hjust = 0,
                  label = paste0("Volatility: 16"), size = 4 ) +
        annotate( geom = "text", x = 504-244, y = 16, color = "purple", hjust = 0,
                  label = paste0("$15"), size = 4 ) +
        annotate("point", x = 504-244, y = 15, colour = "purple") + 
        annotate( geom = "text", x = 285, y = 29, color = "cornflowerblue", hjust = 0,
                  label = paste0("Volatility: 24"), size = 4 ) +
        annotate( geom = "text", x = 504-370, y = 16, color = "cornflowerblue", hjust = 0,
                  label = paste0("$15"), size = 4 ) +
        annotate("point", x = 504-370, y = 15, colour = "cornflowerblue") + 
        geom_curve( aes(x = x1, y = y1, xend = x2, yend = y2), data = annotate_arrow_1,
                    arrow = arrow(length = unit(0.03, "npc")), color = "gray35",
                    curvature = -0.5 ) +
        geom_curve( aes(x = x1, y = y1, xend = x2, yend = y2), data = annotate_arrow_2,
                    arrow = arrow(length = unit(0.03, "npc")), color = "purple" ) +
        geom_curve( aes(x = x1, y = y1, xend = x2, yend = y2), data = annotate_arrow_3,
                    arrow = arrow(length = unit(0.03, "npc")), color = "cornflowerblue" )

temp; rm(temp)
```
