--- 
title: "Understanding Options"
author: "Kamal Rai"
date: "`r Sys.Date()`"
subtitle: ''
site: bookdown::bookdown_site
---

<!-- Pandemic-Proof Your Finances: Pandemic-proof industries -- food, clothing, gasoline, medication... 
Make inspirational - lifestyle changes attributable to living through the pandemic. -->

# Introduction {-}

If you've never seen options before and don't remember the last time you took a math class, this is the book for you. Math is hard, but trading with options doesn't have to be. Options allow you to change the risk-reward characteristics of trades, but they cost money and have a time limit (they *expire*). This books is for anyone who wants to learn how to *think* through options trades. I start by introducing options and the tools you need to understand them - payoff diagrams and the option greeks. The 1^st^ half of the book is the most important, because it teaches you how to think about options. The 2^nd^ half goes through how three different kinds of traders construct and adjust their options trades. 

<!-- I close by looking at options strategies you can use to trade momentum stocks, like the FAANG stocks. This last section shows you how to use the greeks to adjust your options trades, and how to construct more speculative options trades. --> 


## My Trading Life {-}

I started learning when I was 20. I lost around \$15,000 in a few years because I kept making bad decisions. I'd find an investment I liked, watch it go up, and sell it too early. Or I'd watch it go down, hold it for too long, and wait a couple of months for it to bounce back. It usually didn't, so I'd sell and take big losses. I was picking twice as many winners as losers, but still losing money. It took me a while to realize I was the problem. When I had gains, I was so afraid of losing them I'd sell too quickly and only make a little bit. And when I had losses, I didn't want to take them so I'd hold on too long and take big losses. After a few big losses, I had lost almost all the money I started with. 

I didn't like losing money, so I started looking for the holy grail -- a surefire way to make money. I wanted to know the secret the pros were using, how they made their money. I started by looking at people who made money when the US housing market burst. If those guys got that "right", they must be brilliant traders. The more I looked into it, though, the more I realized that they had gotten that call about as wrong as I got my trades. Lots of them made the trade early and had to wait a long time before it started working. They had to carry losses while the housing market kept going up, until it finally crashed. 

That's when I realized that making "picks" isn't a great ways to make money. No matter  how much research I put into a trade, I'd have to wait a long time for a good chunk of my trades to start working. That's not a good way to make money, so I started looking for new ways. That led to me learning about options. Since I'm a self-taught trader, I know how many books on trading the stock market are out there. I've read a ton of them over the last few years. Books where people tell you how they got rich, how they lost their fortune, technical ones that get very mathematical, and everything in between. 

For options, [The Options Playbook](https://www.optionsplaybook.com/) is a fanastic resource. It's a rolodex of every option strategy you could ever use. There are online courses and subscription services too, where you can learn about options and follow someone as they make (and adjust) options trades. I subscribe to [Big Picture Trading](https://bigpicturetrading.com/home-page), which is also fantastic. I followed along more frequently when I first started learning about options, and only check it periodically now. There's no end to the resources out there, and when it comes to trading there's always something new to learn.


## Lessons Learned {-}

If all you need is to learn technical jargon and other people's strategies, there would be a lot more successful traders out there. There's a missing ingredient, and that's how to build a trading system that works for *you*. The idea is simple: the secret to becoming a successful trader is finding a trading system that fits your personality. 

<!-- A quick word on language: People get all worked up over being called traders or investors. Traders are short-term charlatans who opportunistically move in and out of stocks, and investors are of upstanding moral character because they hold their investments for the long term. I call myself a trader because it helps keep me keep a flexible mindset. Market conditions are always changing, and positions that work today might not work tomorrow. Being able to admit that your positioning is wrong today (even if it wasn't wrong yesterday) and adapt to new market conditions can save (or make!) you a lot of money. 

That's the most valuable lesson I've learned in the last few years. Here's a good example -- I made some adjustments I never thought I would after Pfizer's November 7^th^ vaccine announcement. I have a dividend portfolio with roughly 25% allocated to REITs, utilities, telecoms, and bonds. It gives 5% in dividends every year and I want to reinvest them. That gives me 5% more in dividends every year. The dividends also go up, by an average of 4% per. So every year I get 8%-10% more in dividends just by holding these positions. At 8% I double my dividends in 9 years and at 10% I double my dividends in just over 7 years. My pie-in-the-sky dream is that the dividends get large enough so that I can live off of them, and I don't want to make changes to the dividend portfolio that take it away from that goal. 

After the Pfizer vaccine news hit, I realized the opportunities that lie in reopening trades. I sold half the REIT and utility positions. That freed up 25% of the portfolio, which I split 50/50 into 2 energy stocks -- Cenovus (CVE) and Suncor (SU). I kept 75% of the portfolio in "safe" dividend-yielding investments, to maintain the long-term goal of growing the dividends over time. To capture more of the upside in my energy positions without allocating more than 25% to energy stocks, I allocated 5% of the energy position (or 1.25% of the portfolio) to SU calls on SU. If SU performs the way I expect, this will double my returns. The risk is that calls, unlike stocks, expire. I can lose the entire 1.5%.if the SU position moves against me. My plan is to reinvest the gains from CVE and SU back into utilities and REITs, so that I can grow the dividends even faster. This is one of the main ways I use options - to help me keep a more conservative portfolio while still capturing upside in the market. 

When I first shifted into Cenovus and Suncor, I didn't know if the trade would work. I still didn't know during Christmas week. I woke up on December 21^st^ to see my half of my CVE gains gone and my SU position almost in the red. But I didn't panic -- I had a system that helped me judge if the selloff was a flash in the pan. That gave me the patience to wait for a few hours to see how things developed. As it turns out, it was a flash in the pan and I successfully avoided panic selling my positions. That's another important lesson I learned this year. It's important to have a trading system to take your emotions out of trading. I like to take gains and let losses run, which isn't a good way to make money. With the COVID-19 headlines spreading doom and gloom all over 2020, I would be a failure of a trader if I didn't have a system. 


## The Plan {-} 

-->

Trades have personalities, too. They behave in different ways. Some are "safe", some are "risky", and they all have their own quirks. Most importantly, they react differently to changing market conditions. The trades you make also have to fit your personality. I think a lot of the resources on trading overlook that, and just give you information. If you haven't traded options before and you're not sure how to put together all that information, the 2^nd^ half of this book goes through how 3 traders use options (differently!) to help them risk-manage their positions. 1 is an aggressive trader, 1 is fairly conservative, and 1 is in between. But before we break down their trades, we need some tools. The 1^st^ tool is payoff diagrams, which let us draw out the profit/loss of any options strategy. They'll be our main tool for understanding how an options strategy behaves. The 2^nd^ one is volatility, which is a key component of options pricing. It's so powerful it can change the way you think about markets all by itself. The 3^rd^ one is the *greeks*, which your broker provides for every option you can buy. Volatility is 1 of the greeks, so we actually only need 2 tools to break down options strategies -- payoff diagrams and the greeks. 

<!-- The 1^st^ half of the book is devoted to building these tools. The 2^nd^ half is a like an expanded version of a trading journal, that walks you through a bunch of options trades. The 3 traders are actually 3 of my accounts, which all have different goals.  So I through how I was thinking about the trade before I made it, why I chose the particular options strategy, how it fit in the larger context of my portfolio, how I was thinking when I made adjustments, and so on. If I made a similar trade in on of the other accounts account, I'll compare them so that you can see the constrast in the different approaches. 

This isn't a book about modeling or math. Models are very useful, but people often think that understanding their options model means they understand options. I think that trusting a model is very dangerous, because they're just approximations of reality. The greeks are derived from an options model, so we'll see how models can be helpful and limiting at the same time when we take them up. -->

<!-- 
## Acknowledgments {-}

This book is written in Rmarkdown using the *bookdown* package, hosted on Netlify, and built using Travis CI. The *Authoring Books and Technical Documents with R Markdown* at https://musing-aryabhata-b16338.netlify.com/ was very helpful in setting up Netlify and Travis CI.  

```{r, results='asis', echo = FALSE, eval = TRUE} 
if(knitr:::pandoc_to() == "html") { 
  cat('## Sign Up For Updates {-} \n Click below to sign up to receive notifications every time new chapters are published \n.') }
if(knitr:::pandoc_to() == "html") { 
  cat('<script async data-uid="244f107410"src="https://hustling-trailblazer-1491.ck.page/244f107410/index.js"></script>') }
```

--> 